# Generated by Django 4.2.4 on 2024-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.TextField(max_length=128, primary_key=True, serialize=False)),
                ('idd', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('numphone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
